import type { Config } from "tailwindcss";

const config = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./scripts/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        app: {
          bg: "var(--app-bg)",
          "bg-soft": "var(--app-bg-soft)",
          surface: "var(--app-surface)",
          "surface-2": "var(--app-surface-2)",
          "surface-3": "var(--app-surface-3)",
          card: "var(--app-card)",
          "card-hover": "var(--app-card-hover)",
          border: "var(--app-border)",
          "border-strong": "var(--app-border-strong)",
          primary: "var(--app-primary)",
          "primary-hover": "var(--app-primary-hover)",
          "primary-soft": "var(--app-primary-soft)",
          secondary: "var(--app-secondary)",
          "secondary-hover": "var(--app-secondary-hover)",
          "secondary-soft": "var(--app-secondary-soft)",
          accent: "var(--app-accent)",
          "accent-soft": "var(--app-accent-soft)",
          text: "var(--app-text)",
          "text-soft": "var(--app-text-soft)",
          "text-muted": "var(--app-text-muted)",
          "text-faint": "var(--app-text-faint)",
          success: "var(--app-success)",
          "success-soft": "var(--app-success-soft)",
          warning: "var(--app-warning)",
          "warning-soft": "var(--app-warning-soft)",
          danger: "var(--app-danger)",
          "danger-soft": "var(--app-danger-soft)",
          info: "var(--app-info)",
          "info-soft": "var(--app-info-soft)",
          qr: "var(--app-qr)",
          "qr-text": "var(--app-qr-text)",
          "qr-surface": "var(--app-qr-surface)",
          "qr-border": "var(--app-qr-border)",
          "qr-muted": "var(--app-qr-muted)",
          overlay: "var(--app-overlay)",
        },
        background: "var(--app-bg)",
        foreground: "var(--app-text)",
        muted: "var(--app-text-faint)",
        "muted-foreground": "var(--app-text-muted)",
        border: "var(--app-border)",
        "border-strong": "var(--app-border-strong)",
        card: "var(--app-card)",
        "card-foreground": "var(--app-text)",
        surface: "var(--app-surface)",
        "surface-2": "var(--app-surface-2)",
        "surface-3": "var(--app-surface-3)",
        primary: "var(--app-primary)",
        "primary-soft": "var(--app-primary-soft)",
        secondary: "var(--app-secondary)",
        "secondary-soft": "var(--app-secondary-soft)",
        accent: "var(--app-accent)",
        "accent-soft": "var(--app-accent-soft)",
        danger: "var(--app-danger)",
        "danger-soft": "var(--app-danger-soft)",
        success: "var(--app-success)",
        "success-soft": "var(--app-success-soft)",
        warning: "var(--app-warning)",
        "warning-soft": "var(--app-warning-soft)",
        info: "var(--app-info)",
        "info-soft": "var(--app-info-soft)",
        qr: "var(--app-qr)",
        "qr-text": "var(--app-qr-text)",
        ring: "var(--app-primary)",
      },
    },
  },
} satisfies Config;

export default config;
